version: "3.9"

services:
  gateway:
    depends_on:
      - postgres
      - redis
      - applications
    container_name: job-tracker-api-gateway
    image: hollowsunsets/api-gateway
    ports:
      - "443:443"
    environment:
      - REDISADDR=job-tracker-redis-container:6379
      - SESSIONKEY=sessionkey
      - POSTGRES_PASSWORD=postgres
      - APPLICATIONADDR=http://job-tracker-applications-microservice
      - DSN=postgres://postgres:%s@job-tracker-postgres-container:5432/postgres?sslmode=disable
  applications:
    depends_on:
      - postgres
    container_name: job-tracker-applications-microservice
    image: hollowsunsets/applications-microservice
    ports:
      - "80:80"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=job-tracker-postgres-container
      - POSTGRES_PORT=5432
      - POSTGRES_DB=postgres
  postgres:
    container_name: job-tracker-postgres-container
    image: hollowsunsets/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    container_name: job-tracker-redis-container
    ports:
      - "6379:6379"
    image: "redis"
    restart: unless-stopped
