version: "3.9"

services:
  gateway:
    depends_on:
      - postgres
      - redis
      - applications
    container_name: job-tracker-api-gateway
    image: hollowsunsets/api-gateway
    ports:
      - "443:443"
    environment:
      - REDISADDR=6379
      - SESSIONKEY=sessionkey
      - POSTGRES_PASSWORD=postgres
      - APPLICATIONADDR=http://applicationMicroservice
      - DSN=postgres://postgres:%s@postgresStore:5432/postgres?sslmode=disable
  applications:
    depends_on: 
      - postgres
    container_name: job-tracker-applications-microservice
    image: hollowsunsets/applications-microservice
  postgres:
    container_name: job-tracker-postgres-container
    image: hollowsunsets/postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=postgres
  redis:
    container_name: job-tracker-redis-container
    ports:
      - "6379:6379"
    image: "redis"
    restart: unless-stopped
